name: C++ CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tests
        run: |
          g++ --version
          g++ -std=c++20 -O2 -Wall -Wextra -pedantic \
            -o tests_run \
            src/twosum.cpp tests/tests.cpp

      - name: Run tests
        run: |
          ./tests_run

